import { requireAdmin } from "@/lib/auth";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

export default async function AdminSitesPage() {
  const user = await requireAdmin();
  const supabase = await createClient();

  const { data: sites, error } = await supabase
    .from("generated_sites")
    .select("*")
    .order("created_at", { ascending: false });

  return (
    <main className="min-h-screen bg-black text-white">
      <div className="mx-auto max-w-7xl px-6 py-20">
        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between mb-8">
          <div>
            <div className="text-xs uppercase tracking-[0.2em] text-zinc-400">
              Sites
            </div>
            <h1 className="mt-3 text-4xl font-semibold tracking-tight">
              Generated Sites
            </h1>
            <p className="mt-3 max-w-2xl text-zinc-400">
              All sites generated by admins or clients.
            </p>
          </div>
        </div>
        <div className="overflow-x-auto rounded-3xl border border-white/10 bg-white/5">
          <table className="min-w-full border-collapse text-left text-sm">
            <thead className="border-b border-white/10 bg-black/30 text-zinc-400">
              <tr>
                <th className="px-4 py-4 font-medium">Business</th>
                <th className="px-4 py-4 font-medium">Subdomain</th>
                <th className="px-4 py-4 font-medium">Type</th>
                <th className="px-4 py-4 font-medium">Status</th>
                <th className="px-4 py-4 font-medium">Owner</th>
                <th className="px-4 py-4 font-medium">Client</th>
                <th className="px-4 py-4 font-medium">Created</th>
              </tr>
            </thead>
            <tbody>
              {(!sites || sites.length === 0) ? (
                <tr>
                  <td colSpan={7} className="px-4 py-10 text-center text-zinc-500">
                    No sites yet.
                  </td>
                </tr>
              ) : (
                sites.map((site: any) => (
                  <tr key={site.id} className="border-b border-white/5 last:border-b-0">
                    <td className="px-4 py-4">{site.business_name}</td>
                    <td className="px-4 py-4 font-mono">{site.subdomain}.deploylocal.app</td>
                    <td className="px-4 py-4">{site.site_type}</td>
                    <td className="px-4 py-4">{site.status}</td>
                    <td className="px-4 py-4">{site.owner_user_id}</td>
                    <td className="px-4 py-4">{site.client_user_id ?? "—"}</td>
                    <td className="px-4 py-4">{site.created_at?.slice(0, 10)}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </main>
  );
}
